---
#
# Ansible managed
#
repository:
  description: Install and configure consul on your system.
  homepage: https://buluma.github.io/
  topics: consul, ansible, molecule, tox, playbook, hacktoberfest
