---
  - become: true
    gather_facts: false
    hosts: all
    name: Converge
    roles:
      - consul_bind_addr: 0.0.0.0
        consul_bootstrap_expect: 1
        consul_encrypt: 6r73CP0icJrap1tsQ17yuqzVguho4/yz+aI/dkVg2Kk=
        consul_services:
          - name: web
            port: 80
            tags:
              - rails
        role: buluma.consul
