---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: ansible-role-consul
      consul_bootstrap_expect: 1
      consul_encrypt: "6r73CP0icJrap1tsQ17yuqzVguho4/yz+aI/dkVg2Kk="
      consul_bind_addr: "0.0.0.0"
      consul_services:
        - name: web
          tags:
            - rails
          port: 80
