---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if consul can run
      ansible.builtin.command:
        cmd: consul --version
      changed_when: false
