---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - ansible.builtin.command:
        cmd: consul --version
      changed_when: false
      name: Check if consul can run
